message: Primary Message
---
spring:
  profiles: secondary

message: Local functionality
---
spring:
  profiles: encrypt

message: Unencrypted message
name: {cipher}AQCp58SudiYoOEhEZSpne6UfkyRVSmF1ijl4+wGJgR1LOx0qajAfFzJDswlkqeZfedKElquvpVawgLli7/ByhL7WYTXfyitTjwXtCn4zgb00jyLqBHL04QYKlGpci4IVql6MCatb8Xtq+oe7Hz4+2bo3xoSZjsTkjCjOh+wvzSBx4JMSHEstlMvx3mAbLybg2LUbEec5laLsz9Lspo+YAtqF/683hwYkvrvttkfgLpuXxes7uArYQklSYIFLocRzd6SRrLz6BN+S2fU1SYVlOG855uOzymWNZTA6dM+K7FumMtpCpW9Apk0jufYDeM2f974Rk3VJZJBNK7A+GOOUpKWof6vDiDDBVFKN+YhfEVrPE4BQoqbj196FC5HL6jCKFLU=
